// <auto-generated />
using System;
using GestorDeTurnos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeTurnos.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820160352_AddTurnoPlantillas")]
    partial class AddTurnoPlantillas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Cancha", b =>
                {
                    b.Property<int>("IdCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdComplejo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioHora")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCancha");

                    b.HasIndex("IdComplejo");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Complejo", b =>
                {
                    b.Property<int>("IdComplejo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdDueno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdComplejo");

                    b.HasIndex("IdDueno");

                    b.ToTable("Complejos");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enviado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTurno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdTurno");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCancha")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdPlantilla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdCancha");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPlantilla");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.TurnoPlantilla", b =>
                {
                    b.Property<int>("IdPlantilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCancha")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPlantilla");

                    b.HasIndex("IdCancha", "DiaSemana", "HoraInicio");

                    b.ToTable("TurnoPlantillas");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Cancha", b =>
                {
                    b.HasOne("GestorDeTurnos.Domain.Entities.Complejo", "Complejo")
                        .WithMany("Canchas")
                        .HasForeignKey("IdComplejo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Complejo", b =>
                {
                    b.HasOne("GestorDeTurnos.Domain.Entities.Usuario", "Dueno")
                        .WithMany("Complejos")
                        .HasForeignKey("IdDueno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dueno");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("GestorDeTurnos.Domain.Entities.Turno", "Turno")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Turno", b =>
                {
                    b.HasOne("GestorDeTurnos.Domain.Entities.Cancha", "Cancha")
                        .WithMany("Turnos")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeTurnos.Domain.Entities.Usuario", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestorDeTurnos.Domain.Entities.TurnoPlantilla", "Plantilla")
                        .WithMany()
                        .HasForeignKey("IdPlantilla")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");

                    b.Navigation("Plantilla");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.TurnoPlantilla", b =>
                {
                    b.HasOne("GestorDeTurnos.Domain.Entities.Cancha", "Cancha")
                        .WithMany("Plantillas")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Cancha", b =>
                {
                    b.Navigation("Plantillas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Complejo", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Turno", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("GestorDeTurnos.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Complejos");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
